# Generated by Django 3.2.16 on 2023-01-31 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='Порядок показа')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('excursion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.excursion')),
            ],
        ),
    ]
