# Generated by Django 4.1.6 on 2023-02-02 08:15

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_alter_image_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursion',
            name='long_description',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Полное описание'),
        ),
    ]
